"""history table 추가3

Revision ID: 0ebe2e175e0f
Revises: d9895543d461
Create Date: 2025-10-25 17:06:13.045419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebe2e175e0f'
down_revision: Union[str, Sequence[str], None] = 'd9895543d461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histories',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_histories_user_id_users')),
    sa.PrimaryKeyConstraint('history_id', name=op.f('pk_histories'))
    )
    op.create_index('ix_hist_user_created', 'histories', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hist_user_created', table_name='histories')
    op.drop_table('histories')
    # ### end Alembic commands ###
