"""initial schema

Revision ID: aa8aa6eb6dd0
Revises: 
Create Date: 2025-10-28 15:26:36.574307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8aa6eb6dd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_uuid', sa.String(length=36), nullable=True),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.String(length=10), nullable=True),
    sa.Column('grade', sa.Enum('GENERAL', 'VIP', name='grade'), nullable=True),
    sa.Column('lastLogin', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('device_uuid', name=op.f('uq_users_device_uuid')),
    sa.UniqueConstraint('nickname', name=op.f('uq_users_nickname'))
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_prompt', sa.String(length=255), nullable=False),
    sa.Column('fixed_prompt', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_events_user_id_users')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_events'))
    )
    op.create_table('histories',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_histories_user_id_users')),
    sa.PrimaryKeyConstraint('history_id', name=op.f('pk_histories'))
    )
    op.create_index('idx_hist_user_room_created', 'histories', ['user_id', 'room_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hist_user_room_created', table_name='histories')
    op.drop_table('histories')
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
